version: 2

sources:
  - name: f1
    database: databricks_platform
    schema: raw
    tables:
      - name: iot_air_temp
      - name: iot_humidity
      - name: iot_track_temp
      - name: iot_air_pressure
      - name: f1_circuits
      - name: f1_constructors
      - name: f1_drivers
      - name: f1_qualifying
      - name: f1_races
      - name: f1_results
      - name: f1_seasons
      - name: f1_sprint_results
      - name: f1_status