version: 2

sources:
  - name: f1
    database: databricks_platform
    schema: raw
    tables:
      - name: iot_air_temp
        loaded_at_field: _airbyte_extracted_at
        freshness:
          warn_after: {count: 1, period: hour}
      - name: iot_humidity
        loaded_at_field: _airbyte_extracted_at
        freshness:
          warn_after: {count: 1, period: hour}
      - name: iot_track_temp
        loaded_at_field: _airbyte_extracted_at
        freshness:
          warn_after: {count: 1, period: hour}
      - name: iot_air_pressure
        loaded_at_field: _airbyte_extracted_at
        freshness:
          warn_after: {count: 1, period: hour}
      - name: f1_circuits
      - name: f1_constructors
      - name: f1_drivers
      - name: f1_qualifying
      - name: f1_races
      - name: f1_results
      - name: f1_seasons
      - name: f1_sprint_results
      - name: f1_status